.\" Copyright (C) 2018 Rafał Frączek
.\"
.\" This file is part of Smart Traffic Meter.
.\"
.\" Smart Traffic Meter is free software:
.\" you can redistribute it and/or modify it under the terms of the GNU General Public License
.\" as published by the Free Software Foundation,
.\" either version 3 of the License, or (at your option) any later version.
.\"
.\" Smart Traffic Meter is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.\" See the GNU General Public License for more details.
.\"
.\"You should have received a copy of the GNU General Public License along with Smart Traffic Meter.
.\" If not, see http://www.gnu.org/licenses/.
.\" Manpage for smarttrafficmeter.
.\" Contact rafalfr@protonmail.ch to correct errors or typos.

.TH smarttrafficmeter 1 "November 16, 2016" "Smart Traffic Meter .57.0" "Smart Traffic Meter Manual"
.SH NAME
smarttrafficmeter \- tool for measuring network usage
.SH SYNOPSIS
.B smarttrafficmeter [option]

.SH DESCRIPTION
smarttrafficmeter is a program for measuring network usage.
.SH OPTIONS
Options start with one or two dashes.
.IP "-h, --help"
print help info
.IP "-d, --daemon"
run the program as a daemon
.SH SEE ALSO
.BR smarttrafficmeter (1)
.SH BUGS
No known bugs.
.SH AUTHOR
Rafał Frączek (rafalfr@protonmail.ch) 
