.\" Manpage for smarttrafficmeter.
.\" Contact rafalfr@protonmail.ch to correct errors or typos.
.TH man 8 "06 May 2010" "1.0" "smarttrafficmeter man page"
.SH NAME
smarttrafficmeter \- tool for measuring network usage
.SH SYNOPSIS
.B smarttrafficmeter [option]

.SH DESCRIPTION
smarttrafficmeter is a program for measuring network usage.
.SH OPTIONS
Options start with one or two dashes.
.IP --h
print help info
.IP "-d --daemon" run the program as a daemon
.SH SEE ALSO

.SH BUGS
No known bugs.
.SH AUTHOR
Rafał Frączek (rafalfr@protonmail.ch) 
